### PR TITLE
Improve package structure and maintenance

### LINKED ISSUE #18: Installation fails to pull pyaml from PyPI
I installed this project using pip within a very simple conda environment with just Python3 and pip.

The installation seems to be fine, but it fails to install the required `pyyaml` package.

Right now I don't know the cause of this issue, but from what I can see at least the way the installation code of this project is a bit old.

I suggest moving to [modern SetupTools](https://setuptools.pypa.io/en/latest/userguide/index.html) in particular configure your package with [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and set the script as an [entry point](https://setuptools.pypa.io/en/latest/userguide/entry_point.html).

If you want I can help with this with a PR.

### PR DESCRIPTION
**Pull request by HealthyPear**
This Pull Requests introduces the following changes:

- use the `src` layout (which is the [recommended](https://packaging.python.org/en/latest/tutorials/packaging-projects/#packaging-python-projects) one for new projects)
- configure the packaging using [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and update the deployment workflow accordingly
- use [setuptools_scm](https://github.com/pypa/setuptools_scm/) for the package version discovery
- add a conda environment style for developers
- add a Continuous Integration workflow that tests the installation of the package both as a user and as a developer plus the build of the documentation
- update the documentation by not uploading the build material, updated `sphinx-build` options and instructions for developers

Fixes #18

### CODE REVIEW

**Comment by HealthyPear** [comment]
@johannct you need to approve the workflow as I am a first-time contributor

you should also protect the master branch with the checks provided by the new CI workflow

**Comment by HealthyPear** [comment]
@johannct I forgot to tell the CI to actually fetch the repo in the installation test jobs

now it should work but you need to re-approve the workflows

**Comment by johannct** [comment]
What is the best way to avoid having to approve running the CI each time?

**Comment by HealthyPear** [comment]
By the way, in the meantime, the workflows have passed and I think that the next time (if any) you don't need to do it again (for me).

**Comment by HealthyPear** [comment]
but now you should activate these status checks to protect the master branch

**Comment by johannct** [comment]
I am not the owner of the repo. @nicolaschotard is. So I do not have access to the settings

**Comment by HealthyPear** [comment]
@nicolaschotard I suggest you to do it then, so if someone proposes any change you can at least check that they do not break the installation

Have you ever thought about any tests for the main script?

I am thinking of something like mocking up an external server with Python or an external library and testing that you can e.g. add a cell to a notebook.

**Comment by nicolaschotard** [comment]
Hi @HealthyPear !

**Pull request merged**
